pipeline {
agent any

tools {
maven 'mvn'
}

environment {
GIT_URL = 'https://github.com/jeanccsx/spring-rest-webservices-demo.git'
}

stages {
stage('Checkout') {
steps {
git branch: 'master', url: "${GIT_URL}"
}
}

stage('Build') {
steps {
bat "mvn clean package -Dmaven.test.failure.ignore=true"
}
}

stage('Test') {
steps {
bat "mvn test"
}
}
}
}